// packages/vue/src/components/blocks/ContactForm.vue
<script setup lang="ts">
import { ref, computed, useId } from 'vue';
import { cn } from '@/lib/utils';
import Card from '../Card.vue';
import CardHeader from '../CardHeader.vue';
import CardTitle from '../CardTitle.vue';
import CardDescription from '../CardDescription.vue';
import CardBody from '../CardBody.vue';
import Input from '../Input.vue';
import Textarea from '../Textarea.vue';
import Button from '../Button.vue';
import Label from '../Label.vue';

export interface ContactFormValues {
  name: string;
  email: string;
  subject: string;
  message: string;
}

interface Props {
  /** 카드 제목 */
  title?: string;
  /** 카드 설명 */
  description?: string;
  class?: string;
}

withDefaults(defineProps<Props>(), {
  title: '문의하기',
  description: '궁금한 점이 있으시면 아래 양식을 작성해주세요.',
});

const emit = defineEmits<{ submit: [values: ContactFormValues] }>();

const uid = useId();
const nameId = `${uid}-name`;
const emailId = `${uid}-email`;
const subjectId = `${uid}-subject`;
const messageId = `${uid}-message`;

const name = ref('');
const email = ref('');
const subject = ref('');
const message = ref('');

const canSubmit = computed(
  () => !!name.value && !!email.value && !!subject.value && !!message.value
);

const handleSubmit = () => {
  emit('submit', {
    name: name.value,
    email: email.value,
    subject: subject.value,
    message: message.value,
  });
};
</script>

<template>
  <Card variant="outlined" :class="cn('w-full max-w-lg', $props.class)">
    <CardHeader>
      <CardTitle>{{ title }}</CardTitle>
      <CardDescription>{{ description }}</CardDescription>
    </CardHeader>

    <CardBody>
      <form class="space-y-4" @submit.prevent="handleSubmit">
        <div class="flex gap-4">
          <div class="flex-1 space-y-2">
            <Label :for="nameId">이름</Label>
            <Input
              :id="nameId"
              v-model="name"
              type="text"
              placeholder="이름"
              autocomplete="name"
              clearable
            />
          </div>
          <div class="flex-1 space-y-2">
            <Label :for="emailId">이메일</Label>
            <Input
              :id="emailId"
              v-model="email"
              type="email"
              placeholder="이메일"
              autocomplete="email"
              clearable
            />
          </div>
        </div>

        <div class="space-y-2">
          <Label :for="subjectId">제목</Label>
          <Input
            :id="subjectId"
            v-model="subject"
            type="text"
            placeholder="문의 제목을 입력하세요"
            clearable
          />
        </div>

        <div class="space-y-2">
          <Label :for="messageId">내용</Label>
          <Textarea
            :id="messageId"
            v-model="message"
            placeholder="문의 내용을 입력하세요"
            :rows="5"
          />
        </div>

        <Button
          type="submit"
          variant="primary"
          class="w-full"
          :disabled="!canSubmit"
        >
          문의 보내기
        </Button>
      </form>
    </CardBody>
  </Card>
</template>

// packages/react/src/components/blocks/contact-form.tsx
'use client';

import * as React from 'react';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardBody,
} from '../card';
import { Input } from '../input';
import { Textarea } from '../textarea';
import { Button } from '../button';
import { Label } from '../label';
import { cn } from '@/lib/utils';

export interface ContactFormProps {
  /** 폼 제출 핸들러 */
  onSubmit?: (data: {
    name: string;
    email: string;
    subject: string;
    message: string;
  }) => void;
  /** 추가 className */
  className?: string;
  /** 카드 제목 */
  title?: string;
  /** 카드 설명 */
  description?: string;
}

export function ContactForm({
  onSubmit,
  className,
  title = '문의하기',
  description = '궁금한 점이 있으시면 아래 양식을 작성해주세요.',
}: ContactFormProps) {
  const [name, setName] = React.useState('');
  const [email, setEmail] = React.useState('');
  const [subject, setSubject] = React.useState('');
  const [message, setMessage] = React.useState('');
  // 한 페이지에 폼이 여러 개여도 label↔input 연결이 깨지지 않도록 한다
  const uid = React.useId();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit?.({ name, email, subject, message });
  };

  return (
    <Card variant="outlined" className={cn('w-full max-w-lg', className)}>
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>

      <CardBody>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-4">
            <div className="flex-1 space-y-2">
              <Label htmlFor={`${uid}-name`}>이름</Label>
              <Input
                id={`${uid}-name`}
                type="text"
                placeholder="이름"
                value={name}
                onChange={(e) => setName(e.target.value)}
                clearable
                autoComplete="name"
              />
            </div>
            <div className="flex-1 space-y-2">
              <Label htmlFor={`${uid}-email`}>이메일</Label>
              <Input
                id={`${uid}-email`}
                type="email"
                placeholder="이메일"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                clearable
                autoComplete="email"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor={`${uid}-subject`}>제목</Label>
            <Input
              id={`${uid}-subject`}
              type="text"
              placeholder="문의 제목을 입력하세요"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              clearable
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor={`${uid}-message`}>내용</Label>
            <Textarea
              id={`${uid}-message`}
              placeholder="문의 내용을 입력하세요"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              rows={5}
              autoResize
            />
          </div>

          <Button
            type="submit"
            variant="primary"
            className="w-full"
            disabled={!name || !email || !subject || !message}
          >
            문의 보내기
          </Button>
        </form>
      </CardBody>
    </Card>
  );
}
